### ISSUE TITLE
paramiko.ssh_exception.SSHException: No existing session

### ISSUE THREAD

**Issue by ghost** [microsoft/routeros-scanner#18]
I ran into this issue when trying to test my router, it seems to be a common issue with paramiko. 

The fix was to add `look_for_keys=False` to main.py:
```python
ssh_client.connect(hostname=args.ip, port=args.port, username=args.userName, password=args.password, look_for_keys=False)
```

Some people on the internet also suggest to add `allow_agent=False`

Can you possibly add this to readme-file?

**Comment by Sallaxer** [comment]
Same problem. I added both` allow_agent=False` & `look_for_keys=False`

**Comment by noafru** [comment]
Hi, we uploaded several in-house fixes, one of them for this issue. You can see the updates here: https://github.com/microsoft/routeros-scanner/pull/24
