### ISSUE TITLE
How does the command works with paramiko？

### ISSUE THREAD

**Issue by thinkycx** [microsoft/routeros-scanner#20]
For example,  the project use paramiko to run command on the server. 
However, the `/ip` command is not on the server, why it works？

```python
data = self._ssh_data(sshc, '/ip dns print')

stdin, stdout, stderr = sshc.exec_command(command)
```

**Comment by noafru** [comment]
Hi, this tool is for Mikrotik devices which run RouterOS. The RouterOS has a unique SSH shell with custom commands that won't work on a classic Linux shell. One of those commands is the '/ip' command.
